
module ddsx {
	struct CortoDeclare {
		string parent;
		string name;
		string type;
	};
	#pragma keylist CortoDeclare parent name

	struct CortoUpdate {
		string id;
		string value;
	};
	#pragma keylist CortoUpdate id

	struct CortoInvoke {
		string instance;
		string method;
		sequence<octet> args;
	};
	#pragma keylist CortoInvoke
};
